### ISSUE TITLE
A prolem found

### ISSUE THREAD

**Issue by wasted123** [Tee7even/Presents#1]
I have a problem with the plugin Present, it always occur erros when using and when launching.

**Comment by Tee7even** [comment]
Okay, you have made it to GitHub, so you probably understand what you are reading. That's good. 
Have you seen the template when you was creating an issue? It is there not to be removed and replaced by generic "a problem found". It is there to be followed. **I can not help you or fix the bug if I don't understand WHAT EXACTLY is happening.**
So, *please*, create a new issue and fill the template correctly - provide a detailed description of what is happening (it may be server crashing, something going wrong, or just a message in the console), version of Presents and Nukkit build number, crash dump or error output in the console. And then I'll will be probably able to understand and help you.
