### ISSUE TITLE
/placechest crash server

### ISSUE THREAD

**Issue by PetteriM1** [Tee7even/Presents#6]
Issue description
/placechest crash server with new Nukkit version.

Steps to reproduce the issue
Use /placechest in Nukkit 1.1.0 server.

Versions
* Presents version: 1.5
* Nukkit version: 1.1.0

Crashdump or console output
[2017-6-8 19.10.35.log.txt](https://github.com/Tee7even/Presents/files/1061652/2017-6-8.19.10.35.log.txt)

**Comment by karpovichv** [comment]
There's no Nukkit for 1.1.0 yet.
